//! What this binary is, in detail: the version it reports, the source it was
//! built from, and the toolchain that built it.
//!
//! Included by both applications with `#[path = "../build_info.rs"] mod
//! build_info;`. It is a shared *source file* rather than a workspace crate
//! on purpose — see the header of `apps/build_identity.rs`, the build-script
//! half that generates the `BUILD_INFO` constant this file includes.
//!
//! Every field is resolved at build time except `executable`, which answers
//! "which copy of the binary is this?" — the question that matters when a
//! service, a Chocolatey shim, and a hand-built exe all exist on one machine.

// The two binaries deliberately use different subsets: only the CLI reports a
// protocol version, and only it needs the short-vs-long version split. A
// shared module means the unused half is dead in the other binary.
#![allow(dead_code)]

use std::fmt::Write as _;

/// Build-time provenance, generated by `apps/build_identity.rs`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BuildInfo {
    /// The version in `Cargo.toml` — what the next release will be called.
    pub release_version: &'static str,
    /// What this particular build calls itself; equals `release_version`
    /// only for a tagged release build.
    pub version: &'static str,
    /// `release`, `ci`, or `development`.
    pub channel: &'static str,
    pub git_commit: Option<&'static str>,
    pub git_short_commit: Option<&'static str>,
    pub git_branch: Option<&'static str>,
    /// Commits between the last release tag and this build.
    pub revision_count: Option<u64>,
    /// The release tag on the built commit, if any.
    pub source_tag: Option<&'static str>,
    /// Whether the worktree had uncommitted changes at build time.
    pub dirty: bool,
    pub ci_run_id: Option<&'static str>,
    pub ci_run_number: Option<u64>,
    pub ci_run_attempt: Option<u64>,
    pub ci_run_url: Option<&'static str>,
    pub target: &'static str,
    pub host: &'static str,
    pub profile: &'static str,
    pub opt_level: &'static str,
    pub rustc: Option<&'static str>,
}

include!(concat!(env!("OUT_DIR"), "/crossover_build_info.rs"));

/// The version string for `--version`, logs, and the wire handshake.
pub const VERSION: &str = BUILD_INFO.version;

/// One reported value. The variants exist so the JSON rendering can emit
/// numbers, booleans, and `null` as themselves rather than as strings.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Value {
    Text(String),
    OptText(Option<String>),
    Bool(bool),
    Num(u64),
    OptNum(Option<u64>),
}

impl Value {
    fn text(value: &str) -> Self {
        Self::Text(value.to_owned())
    }

    fn opt_text(value: Option<&str>) -> Self {
        Self::OptText(value.map(str::to_owned))
    }
}

/// Answer `--version` / `-V` (add `--json` for a machine-readable object) and
/// report whether that is all this invocation wanted.
///
/// Shared by the two windowless binaries — the service daemon and the layout
/// editor — rather than written out in each. Deliberately not clap: two flags
/// do not justify an argument parser in binaries whose dependency graphs are
/// themselves architectural decisions (ADR 0011, ADR 0019). `crossover.exe`
/// does not use it: its clap definition owns `--version` and appends the
/// protocol range.
///
/// One implementation rather than two matters beyond tidiness —
/// `scripts/build.ps1` checks that every shipped binary reports the same
/// build, and two copies of this parser could drift into disagreeing about
/// what counts as asking.
pub fn reported_version() -> bool {
    let mut asked = false;
    let mut json = false;
    for argument in std::env::args().skip(1) {
        match argument.as_str() {
            "--version" | "-V" => asked = true,
            "--json" => json = true,
            _ => {}
        }
    }
    if asked {
        print!("{}", report(&[], json));
    }
    asked
}

/// Render the full report. `extra` is appended verbatim, letting a binary add
/// facts this module cannot know (the CLI adds the protocol range; the
/// service and the editor have none to add).
pub fn report(extra: &[(&'static str, Value)], json: bool) -> String {
    let mut fields = fields();
    fields.extend(extra.iter().cloned());
    if json {
        render_json(&fields)
    } else {
        render_text(&fields, Headline::WithName)
    }
}

/// The same text report for clap's `--version`, which prints the binary name
/// itself — so the headline here must not repeat it.
pub fn long_version(extra: &[(&'static str, Value)]) -> String {
    let mut fields = fields();
    fields.extend(extra.iter().cloned());
    render_text(&fields, Headline::VersionOnly)
}

/// Whether the report's first line names the binary.
#[derive(Clone, Copy, Eq, PartialEq)]
enum Headline {
    WithName,
    VersionOnly,
}

/// The build-time and process facts, in reporting order.
fn fields() -> Vec<(&'static str, Value)> {
    let info = &BUILD_INFO;
    vec![
        ("name", Value::text(env!("CARGO_PKG_NAME"))),
        ("version", Value::text(info.version)),
        ("release_version", Value::text(info.release_version)),
        ("channel", Value::text(info.channel)),
        ("git_commit", Value::opt_text(info.git_commit)),
        ("git_short_commit", Value::opt_text(info.git_short_commit)),
        ("git_branch", Value::opt_text(info.git_branch)),
        ("source_tag", Value::opt_text(info.source_tag)),
        ("commits_since_tag", Value::OptNum(info.revision_count)),
        ("dirty", Value::Bool(info.dirty)),
        ("ci_run_id", Value::opt_text(info.ci_run_id)),
        ("ci_run_number", Value::OptNum(info.ci_run_number)),
        ("ci_run_attempt", Value::OptNum(info.ci_run_attempt)),
        ("ci_run_url", Value::opt_text(info.ci_run_url)),
        ("target", Value::text(info.target)),
        ("host", Value::text(info.host)),
        ("profile", Value::text(info.profile)),
        ("opt_level", Value::text(info.opt_level)),
        ("debug_assertions", Value::Bool(cfg!(debug_assertions))),
        ("rustc", Value::opt_text(info.rustc)),
        ("executable", Value::OptText(executable_path())),
    ]
}

/// The path of the running binary. `None` rather than a failure: not knowing
/// where you are is a detail to omit, never a reason to fail `--version`.
fn executable_path() -> Option<String> {
    std::env::current_exe()
        .ok()
        .map(|path| path.display().to_string())
}

/// A human-readable block: a headline, then aligned `label  value` rows.
fn render_text(fields: &[(&'static str, Value)], headline: Headline) -> String {
    let name = if headline == Headline::WithName {
        concat!(env!("CARGO_PKG_NAME"), " ")
    } else {
        ""
    };
    let mut report = format!(
        "{name}{} ({} build)\n",
        BUILD_INFO.version, BUILD_INFO.channel,
    );
    // The headline already carries name and version; repeating them in the
    // table would be noise.
    let rows: Vec<&(&'static str, Value)> = fields
        .iter()
        .filter(|(key, _)| *key != "name" && *key != "version")
        .collect();
    let width = rows
        .iter()
        .map(|(key, _)| key.len())
        .max()
        .unwrap_or_default();
    for (key, value) in rows {
        let label = key.replace('_', " ");
        // Pad against the key length: labels only substitute spaces for
        // underscores, so the two are the same width.
        let padding = " ".repeat(width - key.len());
        writeln!(report, "  {label}{padding}  {}", display(value))
            .expect("writing to a String cannot fail");
    }
    report
}

/// A value as it appears in the text report. Absent values read as `(none)`
/// so a row is never silently blank.
fn display(value: &Value) -> String {
    match value {
        Value::Text(text) => text.clone(),
        Value::OptText(text) => text.clone().unwrap_or_else(|| "(none)".to_owned()),
        Value::Bool(flag) => (if *flag { "yes" } else { "no" }).to_owned(),
        Value::Num(number) => number.to_string(),
        Value::OptNum(number) => number.map_or_else(|| "(none)".to_owned(), |n| n.to_string()),
    }
}

/// A pretty-printed JSON object, for scripts and support bundles.
///
/// Hand-rolled rather than pulling in a serializer: the shape is a flat
/// object of scalars, and the service binary's dependency graph is a
/// security boundary that a formatting convenience should not touch
/// (ADR 0011).
fn render_json(fields: &[(&'static str, Value)]) -> String {
    let mut json = String::from("{\n");
    for (index, (key, value)) in fields.iter().enumerate() {
        let separator = if index + 1 == fields.len() { "" } else { "," };
        let rendered = match value {
            Value::Text(text) => quote(text),
            Value::OptText(text) => text.as_deref().map_or_else(|| "null".to_owned(), quote),
            Value::Bool(flag) => flag.to_string(),
            Value::Num(number) => number.to_string(),
            Value::OptNum(number) => {
                number.map_or_else(|| "null".to_owned(), |number| number.to_string())
            }
        };
        writeln!(json, "  {}: {rendered}{separator}", quote(key))
            .expect("writing to a String cannot fail");
    }
    json.push_str("}\n");
    json
}

/// A JSON string literal. Values here are build metadata and a filesystem
/// path, so escaping is not theoretical — a Windows path is full of
/// backslashes.
fn quote(value: &str) -> String {
    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('"');
    for character in value.chars() {
        match character {
            '"' => quoted.push_str("\\\""),
            '\\' => quoted.push_str("\\\\"),
            '\n' => quoted.push_str("\\n"),
            '\r' => quoted.push_str("\\r"),
            '\t' => quoted.push_str("\\t"),
            // Everything below 0x20 must be escaped; \u is the only form
            // that covers the ones without a shorthand.
            control if control < '\u{20}' => {
                write!(quoted, "\\u{:04x}", control as u32)
                    .expect("writing to a String cannot fail");
            }
            other => quoted.push(other),
        }
    }
    quoted.push('"');
    quoted
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_build_version_starts_with_the_release_version() {
        assert!(
            BUILD_INFO.version.starts_with(BUILD_INFO.release_version),
            "build version {} must extend release version {}",
            BUILD_INFO.version,
            BUILD_INFO.release_version,
        );
    }

    #[test]
    fn the_channel_is_one_of_the_three_known_channels() {
        assert!(
            ["release", "ci", "development"].contains(&BUILD_INFO.channel),
            "unexpected channel {}",
            BUILD_INFO.channel,
        );
    }

    #[test]
    fn a_release_build_is_exactly_the_release_version() {
        if BUILD_INFO.channel == "release" {
            // One assertion over a tuple: each field is a constant in any
            // given build, which `assert!` alone would (rightly) flag.
            assert_eq!(
                (
                    BUILD_INFO.version,
                    BUILD_INFO.dirty,
                    BUILD_INFO.source_tag.is_some()
                ),
                (BUILD_INFO.release_version, false, true),
            );
        }
    }

    #[test]
    fn the_text_report_names_every_field_it_was_given() {
        let report = report(&[("protocol_version", Value::Num(2))], false);
        assert!(report.starts_with(concat!(env!("CARGO_PKG_NAME"), " ")));
        // clap prints the binary name before `--version`, so this form must
        // start at the version or the name appears twice.
        assert!(long_version(&[]).starts_with(BUILD_INFO.version));
        assert!(report.contains("git commit"));
        let protocol = report
            .lines()
            .find(|line| line.trim_start().starts_with("protocol version"))
            .expect("the extra field appears as its own row");
        assert!(protocol.ends_with(" 2"), "unexpected row: {protocol}");
        // The headline covers these; the table must not repeat them.
        assert!(!report.contains("\n  version "));
    }

    #[test]
    fn the_json_report_is_a_flat_object_of_scalars() {
        let report = report(&[("protocol_version", Value::Num(2))], true);
        assert!(report.starts_with("{\n"));
        assert!(report.ends_with("}\n"));
        assert!(report.contains("\"protocol_version\": 2\n"));
        assert!(report.contains("\"dirty\": "));
        // A trailing comma is the classic hand-rolled-JSON bug.
        assert!(!report.contains(",\n}"));
    }

    #[test]
    fn json_strings_escape_quotes_backslashes_and_control_characters() {
        assert_eq!(
            quote(r"C:\Program Files\Crossover"),
            r#""C:\\Program Files\\Crossover""#
        );
        assert_eq!(quote("say \"hi\""), r#""say \"hi\"""#);
        assert_eq!(quote("line\nbreak\ttab"), r#""line\nbreak\ttab""#);
        assert_eq!(quote("bell\u{7}"), r#""bell\u0007""#);
    }

    #[test]
    fn absent_values_read_as_none_in_text_and_null_in_json() {
        let absent = [("nothing", Value::OptText(None))];
        assert!(render_text(&absent, Headline::WithName).contains("nothing  (none)"));
        assert!(render_json(&absent).contains("\"nothing\": null"));
    }
}
